<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Form for create Ases User
 *
 * @author     Luis Gerardo Manrique Cardona
 * @package    block_ases
 * @copyright  2018 Luis Gerardo Manrique Cardona <luis.manrique@correounivalle.edu.co>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die;
require_once($CFG->dirroot.'/user/editadvanced_form.php');
class moodle_user_creation_ases_version extends user_editadvanced_form {
    function after_definition()
    {
        parent::after_definition(); // TODO: Change the autogenerated stub
        $mform = $this->_form;
        /* First name and Last name aditional validations*/
        $mform->addRule('fistname', 'El nombre debe contener letras mayusculas (almenos 2) y espacios, ademas debe tener una letra al inicio', 'regex', '/^[A-Z]{1,}(?=.*[A-Z])([A-Z ]{2,}+)$/');
        $mform->addRule('lastname', 'El apellido debe contener letras mayusculas (almenos 2) y espacios, ademas debe tener una letra al inicio', 'regex', '/^[A-Z]{1,}(?=.*[A-Z])([A-Z ]{2,}+)$/');

    }

    function definition_after_data()
    {
        $mform = $this->_form;
        if ($mform->elementExists('deletepicture')) {
            $mform->removeElement('deletepicture');
        }
        if ($mform->elementExists('currentpicture')) {
            $mform->removeElement('currentpicture');
        }
        if ($mform->elementExists('imagefile')) {
            $mform->removeElement('imagefile');
        }
        if ($mform->elementExists('imagealt')) {
            $mform->removeElement('imagealt');
        }

    }
}