<?php
require_once(dirname(__FILE__). '/../../../config.php');
require('query.php');
    global $DB;
    $updateAsig1 = "UPDATE {talentospilos_seg_estudiante} SET id_estudiante = 152 WHERE id_seguimiento = 24069";
    $updateAsig2 = "UPDATE {talentospilos_seg_estudiante} SET id_estudiante = 152 WHERE id_seguimiento = 24135";
    $updateAsig3 = "UPDATE {talentospilos_seg_estudiante} SET id_estudiante = 152 WHERE id_seguimiento = 24136";

    echo $DB->execute($updateAsig1);
    echo $DB->execute($updateAsig2);
    echo $DB->execute($updateAsig3);
    
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25749, 'id_estudiante'=>888);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25671, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25431, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25421, 'id_estudiante'=>133);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25397, 'id_estudiante'=>202);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25344, 'id_estudiante'=>897);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25007, 'id_estudiante'=>888);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25005, 'id_estudiante'=>133);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24990, 'id_estudiante'=>133);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24966, 'id_estudiante'=>888);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24965, 'id_estudiante'=>888);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24960, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24937, 'id_estudiante'=>888);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24776, 'id_estudiante'=>202);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24672, 'id_estudiante'=>897);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24556, 'id_estudiante'=>894);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24539, 'id_estudiante'=>893);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24498, 'id_estudiante'=>202);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24456, 'id_estudiante'=>888);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24325, 'id_estudiante'=>888);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24261, 'id_estudiante'=>905);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24088, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24063, 'id_estudiante'=>894);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24040, 'id_estudiante'=>897);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24013, 'id_estudiante'=>897);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>24009, 'id_estudiante'=>202);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23993, 'id_estudiante'=>133);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23928, 'id_estudiante'=>202);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23773, 'id_estudiante'=>888);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23753, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23681, 'id_estudiante'=>205);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23633, 'id_estudiante'=>133);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23629, 'id_estudiante'=>888);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23609, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23608, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23592, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23564, 'id_estudiante'=>202);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23559, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23451, 'id_estudiante'=>894);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23301, 'id_estudiante'=>897);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23220, 'id_estudiante'=>894);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23174, 'id_estudiante'=>888);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>23156, 'id_estudiante'=>202);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22939, 'id_estudiante'=>199);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22935, 'id_estudiante'=>905);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22847, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22838, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22832, 'id_estudiante'=>133);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22809, 'id_estudiante'=>205);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22783, 'id_estudiante'=>897);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22738, 'id_estudiante'=>897);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22678, 'id_estudiante'=>133);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22619, 'id_estudiante'=>133);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22567, 'id_estudiante'=>897);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22544, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22419, 'id_estudiante'=>133);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22264, 'id_estudiante'=>202);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22200, 'id_estudiante'=>133);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22155, 'id_estudiante'=>891);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>22046, 'id_estudiante'=>202);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25621, 'id_estudiante'=>912);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25617, 'id_estudiante'=>912);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25616, 'id_estudiante'=>912);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25615, 'id_estudiante'=>912);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25614, 'id_estudiante'=>912);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25613, 'id_estudiante'=>912);
echo $DB->insert_record('talentospilos_seg_estudiante',array('id_seguimiento'=>25482, 'id_estudiante'=>912);